name: Infraestrutura AWS

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Criar terraform.tfvars com secrets
        run: |
          echo 'aws_region = "us-east-1"' > terraform.tfvars
          echo 'ecr_repo_name = "hr-conversational-ai-backend"' >> terraform.tfvars
          echo 's3_bucket_name = "hr-conversational-ai-frontend"' >> terraform.tfvars
          echo 'ecs_cluster_name = "hr-conversational-ai-cluster"' >> terraform.tfvars
          echo 'gemini_api_key = "${{ secrets.GEMINI_API_KEY }}"' >> terraform.tfvars

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars"